### ISSUE TITLE
Remove eigen external libraries

### ISSUE THREAD

**Issue by vissarion** [GeomScale/volesti#114]
**Is your feature request related to a problem? Please describe.**
External libraries consume space in the repository and have to be updated manually.

**Describe the solution you'd like**
Remove them from `external` folder and download them in `cmake` before building the package or whenever needed. This should be straightforward for the cases of `boost` and `eigen`. For `lpsolve` removing from external could be more complicated. 

**EDIT:** to make the procedure more clear we stick with `eigen` in this issue and we will open specified issues for the rest of the libraries

**Comment by vishkrish200** [comment]
Hey,

Can I take this issue up?
It would be my first

**Comment by TolisChal** [comment]
Yes of course. You could work on a new PR.

**Comment by vishkrish200** [comment]
Hey,

I am not so familiar with c++ libraries and cmake.
Am I to link the various external libraries in the eigen and boost folders by creating a CMakeLists.txt file for each library?

**Comment by vissarion** [comment]
I guess there are many possible solutions. One could be to remove the
library from external folder and add some commands to CMakeList in order to
download the needed files before compilation.

**Comment by vishkrish200** [comment]
when you refer to the CMakeList file, you're talking about the preexisting one present int the examples folder?

**Comment by vishkrish200** [comment]
When you refer to the CMakeList file, is it the preexisting one in the examples folder?

**Comment by vissarion** [comment]
you should start with the main one in `test` directory

**Comment by vissarion** [comment]
Closed by https://github.com/GeomScale/volume_approximation/pull/131
