### ISSUE TITLE
R interface

### ISSUE THREAD

**Issue by TolisChal** [GeomScale/volesti#117]
Fix / improve the followings:

1) storing Polytope objects in one session and loading them in another leads to
awkward and unexpected errors:
`Error in sprintf("C++ object <%s> of class '%s' <%s>", 
externalptr_address(pointer),'a0 :
'a0 external pointer is not valid`

2) Drop exportPattern("^[[:alpha:]]+") from NAMESPACE file

3) Add flag drop = FALSE to code like  `A = Mat[,-c(1)]`  

4) Change input arguments in R functions. Instead of setting the arguments equal to NULL, check internally
 for NULL and replacing with the default.

5) Remove file_to_polytope R function

**Comment by pradeexsu** [comment]
@vissarion, is this issue still need to do something?, should I work on this if it's needed?

**Comment by NehaAr** [comment]
Can you specify the version of Volesti package used in this case. Latest version does not have this function

**Comment by vissarion** [comment]
It seems that this issue is fixed by https://github.com/GeomScale/volesti/pull/118
So I am closing this now.
