### ISSUE TITLE
Redundant C++ tests

### ISSUE THREAD

**Issue by AlexManochis** [GeomScale/volesti#134]
In folder `test` there are a few `C++` tests for the previous code structure and interface, e.g. `vol.ccp`, that can be safely removed. This will improve the performance of the CI suites.

**Comment by backbencher00** [comment]
Could you please assign this task to me

**Comment by vissarion** [comment]
Please go ahead and submit a PR.

**Comment by surajchoubey** [comment]
```vol.cpp``` is meant to be removed right?
I ran the tests without it and it tests works fine. 
Is it the thing or do you mean to convey something else?

**Comment by vissarion** [comment]
`vol.cpp` is an example. All files that does not appear in the `CMakeList.txt` can be safely removed. Also there could be other tests that appear in ` CMakeList.txt`  are not needed or are duplicates.
