### ISSUE TITLE
Remove boost external libraries

### ISSUE THREAD

**Issue by vissarion** [GeomScale/volesti#140]
**Is your feature request related to a problem? Please describe.**
External libraries consume space in the repository and have to be updated manually.

**Describe the solution you'd like**
Remove `boost` from `external` folder and download them in `cmake` before building the package or whenever needed. 

See how this was done for eigen https://github.com/GeomScale/volume_approximation/pull/131

**Comment by angelosps** [comment]
Hello, 
May I get this one? It will be my first

**Comment by vissarion** [comment]
@angelosps thanks for your interest. There is no permission needed to work on an issue. 
There exist a PR already for this issue https://github.com/GeomScale/volume_approximation/pull/145 
Although this is not a prohibitive fact it is a better idea to choose another issue for your first one.

**Comment by angelosps** [comment]
I will do. Thanks!

**Comment by vaithak** [comment]
I think this can be closed now by #145.

**Comment by vissarion** [comment]
> I think this can be closed now by #145.

FYI, if you link the issue with the PR then when the PR is merged the issue is closed automatically
