### ISSUE TITLE
Remove lpsolve external libraries

### ISSUE THREAD

**Issue by vissarion** [GeomScale/volesti#141]
**Is your feature request related to a problem? Please describe.**
External libraries consume space in the repository and have to be updated manually.

**Describe the solution you'd like**
Remove `lpsolve` from `external` folder and download them in `cmake` before building the package or whenever needed. 

See how this was done for eigen https://github.com/GeomScale/volume_approximation/pull/131

**Comment by backbencher00** [comment]
sir could you assign me this issue, I would like to work on this

**Comment by vissarion** [comment]
No need to ask permission to work on an issue. Please submit a pull request
and this will be reviewed in a first come first serve basis.

**Comment by ManavShah05** [comment]
I have created a pull request here: https://github.com/GeomScale/volume_approximation/pull/149

**Comment by vissarion** [comment]
> I have created a pull request here: #149

 Thanks, please link this issue on your PR (there is a option in the PR page).
