### ISSUE TITLE
Python Interface Installation failed

### ISSUE THREAD

**Issue by hjnnjh** [GeomScale/volesti#174]
**Describe the bug**
When I try to install python interface of the repo, I got this error, shown in the following picture. There is not the boosl/random.hpp file in the repo. I followed the installation guide in the MD file.
![7c28a21849fb4021b20340f6c43a214](https://user-images.githubusercontent.com/37699150/132942314-feb04551-2e77-4339-a4f7-4f1c020909db.png)

**Desktop (please complete the following information):**
ubuntu 18.04 python 3.7 & 3.8

Hope you can check to see if there are any missing files or code errors.

**Comment by vissarion** [comment]
The python interface is moved to a new package https://github.com/GeomScale/dingo 
Please use that package instead, the interface in this repo is deprecated.

**Comment by hjnnjh** [comment]
> The python interface is moved to a new package https://github.com/GeomScale/dingo
> Please use that package instead, the interface in this repo is deprecated.

Thank you!
