### ISSUE TITLE
CMakeLists not creating requested executable. Default executable ( Makefile) fails to run 

### ISSUE THREAD

**Issue by abmukh** [GeomScale/volesti#182]
Created a folder called Sampling within vol-test/Examples to test small sampling codes. Modified an appropriate CMakelist file
![CMakeListsmodified](https://user-images.githubusercontent.com/87852739/136388095-de8100d8-30b0-46ef-b136-c2c9412a82ea.png)
It does not produce the executable as requested , but simply generates a "makefile". Neither does it generate the sub directory as requested. It does however generate the subdirectories that has been commented out. 

![cmake_results](https://user-images.githubusercontent.com/87852739/136389448-62482c20-7002-415b-9b04-386d82e67ccb.png)
The Makefile generated fails to compile, raising an issue with the mkl header, which has been downloaded and installed
![make_error](https://user-images.githubusercontent.com/87852739/136390692-42faa9c2-0ef8-4bc1-803e-4d875ead74f4.png)
Moving to a subdirectory "hpolytope-volume" , it contains an object "hpolytopeVolume" that executes successfully with make 
![hpolvol](https://user-images.githubusercontent.com/87852739/136391230-34a9acf7-a505-4a20-8a52-b229e5c00185.png)

**Comment by vissarion** [comment]
Thanks @abmukh for reporting this issue!

First, please do not include screenshots with code (your `CMakeList.txt` file) but use instead markdown see https://guides.github.com/features/mastering-markdown/

Second, you have to share more information to be able to reproduce your issue. For example, where is your CMakeList.txt saved? I guess in `examples/sampling`. Then `add_subdirectory(sampling)` should be added in the main `CMakeList.txt` in `examples` directory (just like the `hpolytope-volume` example than compiles correctly on your side). `Try1.cpp` code is also missing; I guess it does not include any mkl headers.

Finally, it seems that there is an issue with `mkl` in examples but this is unrelated with creating a new example such as sampling that does not need `mkl` to compile.

**Comment by vissarion** [comment]
This should be fixed by https://github.com/GeomScale/volesti/pull/190 
If still a problem @abmukh please feel free to open the issue again.
