### ISSUE TITLE
Adding License and Contribution Section in README

### ISSUE THREAD

**Issue by Pradumnasaraf** [GeomScale/volesti#185]
- Adding License and Contribution Section in README.
- Instead of simple text adding Hyperlink.
![1](https://user-images.githubusercontent.com/51878265/136592502-4916f864-50ec-4799-9187-2ece0516f632.png)

**Comment by vissarion** [comment]
Thanks for the interest in `volesti`. There is a link in README on Contributing. Regarding license link, I do not found it very important but feel free to propose a PR with that addition. I will happily review it.
