### ISSUE TITLE
Integrate Codecov's Github app with Geomscale

### ISSUE THREAD

**Issue by vaithak** [GeomScale/volesti#191]
**Is your feature request related to a problem? Please describe.**
Codecov has been enabled on the repo by #188. The aim is that whenever a new PR is made, Codecov should report any changes to the coverage as a comment to that PR. 

**Describe the solution you'd like**
This can be done by integrating Codecov's Github app with GeomScale org. I think this can be done by simply installing the Codecov app from here: https://github.com/apps/codecov. More detailed instructions can be followed from https://docs.codecov.com/docs/how-to-create-a-github-app-for-codecov-enterprise

**Comment by vissarion** [comment]
Thanks for this issue. This is addressed by https://github.com/GeomScale/volesti/commit/430d8cf77ccde19afaf6452f4b0c2cdf6bada2de
