### ISSUE TITLE
Instructions for installing volestipy in windows platform

### ISSUE THREAD

**Issue by imitator19** [GeomScale/volesti#198]
I am trying to install the python package volestipy on a computer with win-10 rather than linux. I hope that the instructions for the command line installation of volestipy can be kindly provided. I think there maybe many others like me with a win-10 laptop and eager to explore volesti using python. Thank you!

**Comment by Dhairya3124** [comment]
Hey @imitator19 This issue is similiar to #13.

**Comment by imitator19** [comment]
@Dhairya3124 Thanks!
