### ISSUE TITLE
Sampling polytopes with constraints in equality form

### ISSUE THREAD

**Issue by iakoviid** [GeomScale/volesti#246]
Extend polytope sampling to handle equality form constraints, such as Aeq x=b, x >= lb.

**Comment by TolisChal** [comment]
@vissarion  I think this issue is fixed, isn't it?

**Comment by vissarion** [comment]
Yes, there is `constraint_problem` that support equalities https://github.com/GeomScale/volesti/blob/develop/include/preprocess/crhmc/constraint_problem.h
