### ISSUE TITLE
Set random seed in MC integration

### ISSUE THREAD

**Issue by masinag** [GeomScale/volesti#250]
Currently the `simple_mc_polytope` and `simple_mc_polytope_integrate` functions do not allow to set the random seed to initialize the RNG. This feature is needed for having reproducible results.

A simple solution would be to add a `seed` parameter to such functions and cal the `set_seed` method on the RNGs within the function.

**Comment by vissarion** [comment]
Thanks for your question. 

The random seed is set in https://github.com/GeomScale/volesti/blob/develop/include/generators/boost_random_number_generator.hpp#L60. See for example how this is done for volume computation https://github.com/GeomScale/volesti/blob/develop/test/volume_sob_hpolytope.cpp#L122 (there the seed is `123`). You should be able to do the same for integration functions.

Does this work for you?

**Comment by masinag** [comment]
Yes, thank you. However, in this way the seed has to be known at compile time, we cannot set it with the value of a parameter at runtime. Am I wrong?

**Comment by vissarion** [comment]
There is the `set_seed` https://github.com/GeomScale/volesti/blob/develop/include/generators/boost_random_number_generator.hpp#L47 function that can be used for setting a runtime seed.

**Comment by masinag** [comment]
Yes, that's what I was suggesting. 
However, the RNGs are instantiated within the `simple_mc_polytope_integrate` function, so the function would need a further parameter `seed` to set the seed on the instantiated RNGs.
The RNGs are two, one for the volume computation with `d=P.dimension()`, the other for the points sampling with `d=1`, if I understand correctly

Alternatively, the function can get as parameters the RNGs instead of the seed.

What would you suggest?

**Comment by vissarion** [comment]
I think we should be as close to the interface of volume functions as possible. Thus, this is your second proposal, i.e. to add an `rng` parameter to the integration function. Are you interested to propose a PR with this change? I can help and review it.

**Comment by masinag** [comment]
Sure, thank you!

Related to this, I think there is a bug here 
https://github.com/GeomScale/volesti/blob/7cdeae2a041da36158d25053646f1c28e9578eb5/include/integration/simple_MC_integration.hpp#L154

Shouldn't RNG be initialized with `d=P.dimension()` instead of 1? In fact, I observed strange results while sampling using the CDHR walk, as the random points lied on an axis-aligned line.

In particular, I think we should use the same RNG used for volume computation to sample the random points for the MC estimation.

Are my observations correct?

**Comment by vissarion** [comment]
You are right! The initialization is wrong and probably related to the axis-aligned random points you observe.
